package com.medicineCenter.model.dataObject;

import org.apache.commons.lang.builder.EqualsBuilder;

import java.util.Date;

public class ExpertsLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experts_log.experts_log_id
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    private Integer expertsLogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experts_log.experts_id
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    private Integer expertsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experts_log.name
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experts_log.gender
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experts_log.age
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    private String age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experts_log.school
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    private String school;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experts_log.degree
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    private String degree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experts_log.work
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    private String work;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experts_log.title
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experts_log.phone
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experts_log.remarks
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experts_log.leader
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    private String leader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experts_log.bacteria
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    private String bacteria;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experts_log.category
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experts_log.category_two
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    private String categoryTwo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experts_log.source
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experts_log.CREATE_TIME
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experts_log.attribution
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    private String attribution;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experts_log.create_user
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experts_log.editionNum
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    private Integer editionnum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experts_log.experts_log_id
     *
     * @return the value of experts_log.experts_log_id
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    public Integer getExpertsLogId() {
        return expertsLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experts_log.experts_log_id
     *
     * @param expertsLogId the value for experts_log.experts_log_id
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    public void setExpertsLogId(Integer expertsLogId) {
        this.expertsLogId = expertsLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experts_log.experts_id
     *
     * @return the value of experts_log.experts_id
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    public Integer getExpertsId() {
        return expertsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experts_log.experts_id
     *
     * @param expertsId the value for experts_log.experts_id
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    public void setExpertsId(Integer expertsId) {
        this.expertsId = expertsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experts_log.name
     *
     * @return the value of experts_log.name
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experts_log.name
     *
     * @param name the value for experts_log.name
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experts_log.gender
     *
     * @return the value of experts_log.gender
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experts_log.gender
     *
     * @param gender the value for experts_log.gender
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experts_log.age
     *
     * @return the value of experts_log.age
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experts_log.age
     *
     * @param age the value for experts_log.age
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    public void setAge(String age) {
        this.age = age == null ? null : age.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experts_log.school
     *
     * @return the value of experts_log.school
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experts_log.school
     *
     * @param school the value for experts_log.school
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experts_log.degree
     *
     * @return the value of experts_log.degree
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    public String getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experts_log.degree
     *
     * @param degree the value for experts_log.degree
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    public void setDegree(String degree) {
        this.degree = degree == null ? null : degree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experts_log.work
     *
     * @return the value of experts_log.work
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    public String getWork() {
        return work;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experts_log.work
     *
     * @param work the value for experts_log.work
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    public void setWork(String work) {
        this.work = work == null ? null : work.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experts_log.title
     *
     * @return the value of experts_log.title
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experts_log.title
     *
     * @param title the value for experts_log.title
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experts_log.phone
     *
     * @return the value of experts_log.phone
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experts_log.phone
     *
     * @param phone the value for experts_log.phone
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experts_log.remarks
     *
     * @return the value of experts_log.remarks
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experts_log.remarks
     *
     * @param remarks the value for experts_log.remarks
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experts_log.leader
     *
     * @return the value of experts_log.leader
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    public String getLeader() {
        return leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experts_log.leader
     *
     * @param leader the value for experts_log.leader
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    public void setLeader(String leader) {
        this.leader = leader == null ? null : leader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experts_log.bacteria
     *
     * @return the value of experts_log.bacteria
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    public String getBacteria() {
        return bacteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experts_log.bacteria
     *
     * @param bacteria the value for experts_log.bacteria
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    public void setBacteria(String bacteria) {
        this.bacteria = bacteria == null ? null : bacteria.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experts_log.category
     *
     * @return the value of experts_log.category
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experts_log.category
     *
     * @param category the value for experts_log.category
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experts_log.category_two
     *
     * @return the value of experts_log.category_two
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    public String getCategoryTwo() {
        return categoryTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experts_log.category_two
     *
     * @param categoryTwo the value for experts_log.category_two
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    public void setCategoryTwo(String categoryTwo) {
        this.categoryTwo = categoryTwo == null ? null : categoryTwo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experts_log.source
     *
     * @return the value of experts_log.source
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experts_log.source
     *
     * @param source the value for experts_log.source
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experts_log.CREATE_TIME
     *
     * @return the value of experts_log.CREATE_TIME
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experts_log.CREATE_TIME
     *
     * @param createTime the value for experts_log.CREATE_TIME
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experts_log.attribution
     *
     * @return the value of experts_log.attribution
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    public String getAttribution() {
        return attribution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experts_log.attribution
     *
     * @param attribution the value for experts_log.attribution
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    public void setAttribution(String attribution) {
        this.attribution = attribution == null ? null : attribution.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experts_log.create_user
     *
     * @return the value of experts_log.create_user
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experts_log.create_user
     *
     * @param createUser the value for experts_log.create_user
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experts_log.editionNum
     *
     * @return the value of experts_log.editionNum
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    public Integer getEditionnum() {
        return editionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experts_log.editionNum
     *
     * @param editionnum the value for experts_log.editionNum
     *
     * @mbggenerated Mon Jan 02 16:23:31 CST 2017
     */
    public void setEditionnum(Integer editionnum) {
        this.editionnum = editionnum;
    }

    @Override
    public boolean equals(Object obj) {
        return EqualsBuilder.reflectionEquals(this, obj);
    }
}