package com.medicineCenter.model.dataObject;

import org.apache.commons.lang.builder.EqualsBuilder;

import java.util.Date;

public class TaskUpdateLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_update_log.id
     *
     * @mbggenerated Fri Jan 20 16:20:36 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_update_log.task_id
     *
     * @mbggenerated Fri Jan 20 16:20:36 CST 2017
     */
    private Integer taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_update_log.reason
     *
     * @mbggenerated Fri Jan 20 16:20:36 CST 2017
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_update_log.create_time
     *
     * @mbggenerated Fri Jan 20 16:20:36 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_update_log.create_user
     *
     * @mbggenerated Fri Jan 20 16:20:36 CST 2017
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_update_log.experts_id
     *
     * @mbggenerated Fri Jan 20 16:20:36 CST 2017
     */
    private Integer expertsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_update_log.id
     *
     * @return the value of task_update_log.id
     *
     * @mbggenerated Fri Jan 20 16:20:36 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_update_log.id
     *
     * @param id the value for task_update_log.id
     *
     * @mbggenerated Fri Jan 20 16:20:36 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_update_log.task_id
     *
     * @return the value of task_update_log.task_id
     *
     * @mbggenerated Fri Jan 20 16:20:36 CST 2017
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_update_log.task_id
     *
     * @param taskId the value for task_update_log.task_id
     *
     * @mbggenerated Fri Jan 20 16:20:36 CST 2017
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_update_log.reason
     *
     * @return the value of task_update_log.reason
     *
     * @mbggenerated Fri Jan 20 16:20:36 CST 2017
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_update_log.reason
     *
     * @param reason the value for task_update_log.reason
     *
     * @mbggenerated Fri Jan 20 16:20:36 CST 2017
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_update_log.create_time
     *
     * @return the value of task_update_log.create_time
     *
     * @mbggenerated Fri Jan 20 16:20:36 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_update_log.create_time
     *
     * @param createTime the value for task_update_log.create_time
     *
     * @mbggenerated Fri Jan 20 16:20:36 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_update_log.create_user
     *
     * @return the value of task_update_log.create_user
     *
     * @mbggenerated Fri Jan 20 16:20:36 CST 2017
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_update_log.create_user
     *
     * @param createUser the value for task_update_log.create_user
     *
     * @mbggenerated Fri Jan 20 16:20:36 CST 2017
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_update_log.experts_id
     *
     * @return the value of task_update_log.experts_id
     *
     * @mbggenerated Fri Jan 20 16:20:36 CST 2017
     */
    public Integer getExpertsId() {
        return expertsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_update_log.experts_id
     *
     * @param expertsId the value for task_update_log.experts_id
     *
     * @mbggenerated Fri Jan 20 16:20:36 CST 2017
     */
    public void setExpertsId(Integer expertsId) {
        this.expertsId = expertsId;
    }

    @Override
    public boolean equals(Object obj) {
        return EqualsBuilder.reflectionEquals(this, obj);
    }
}