package com.medicineCenter.model.dataObject;

import org.apache.commons.lang.builder.EqualsBuilder;

import java.util.Date;

public class TaskLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_log.id
     *
     * @mbggenerated Fri Dec 30 14:37:03 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_log.task_id
     *
     * @mbggenerated Fri Dec 30 14:37:03 CST 2016
     */
    private Integer taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_log.orig_experts_id
     *
     * @mbggenerated Fri Dec 30 14:37:03 CST 2016
     */
    private Integer origExpertsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_log.new_experts_id
     *
     * @mbggenerated Fri Dec 30 14:37:03 CST 2016
     */
    private Integer newExpertsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_log.reason
     *
     * @mbggenerated Fri Dec 30 14:37:03 CST 2016
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_log.create_time
     *
     * @mbggenerated Fri Dec 30 14:37:03 CST 2016
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_log.create_user
     *
     * @mbggenerated Fri Dec 30 14:37:03 CST 2016
     */
    private String createUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_log.id
     *
     * @return the value of task_log.id
     *
     * @mbggenerated Fri Dec 30 14:37:03 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_log.id
     *
     * @param id the value for task_log.id
     *
     * @mbggenerated Fri Dec 30 14:37:03 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_log.task_id
     *
     * @return the value of task_log.task_id
     *
     * @mbggenerated Fri Dec 30 14:37:03 CST 2016
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_log.task_id
     *
     * @param taskId the value for task_log.task_id
     *
     * @mbggenerated Fri Dec 30 14:37:03 CST 2016
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_log.orig_experts_id
     *
     * @return the value of task_log.orig_experts_id
     *
     * @mbggenerated Fri Dec 30 14:37:03 CST 2016
     */
    public Integer getOrigExpertsId() {
        return origExpertsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_log.orig_experts_id
     *
     * @param origExpertsId the value for task_log.orig_experts_id
     *
     * @mbggenerated Fri Dec 30 14:37:03 CST 2016
     */
    public void setOrigExpertsId(Integer origExpertsId) {
        this.origExpertsId = origExpertsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_log.new_experts_id
     *
     * @return the value of task_log.new_experts_id
     *
     * @mbggenerated Fri Dec 30 14:37:03 CST 2016
     */
    public Integer getNewExpertsId() {
        return newExpertsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_log.new_experts_id
     *
     * @param newExpertsId the value for task_log.new_experts_id
     *
     * @mbggenerated Fri Dec 30 14:37:03 CST 2016
     */
    public void setNewExpertsId(Integer newExpertsId) {
        this.newExpertsId = newExpertsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_log.reason
     *
     * @return the value of task_log.reason
     *
     * @mbggenerated Fri Dec 30 14:37:03 CST 2016
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_log.reason
     *
     * @param reason the value for task_log.reason
     *
     * @mbggenerated Fri Dec 30 14:37:03 CST 2016
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_log.create_time
     *
     * @return the value of task_log.create_time
     *
     * @mbggenerated Fri Dec 30 14:37:03 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_log.create_time
     *
     * @param createTime the value for task_log.create_time
     *
     * @mbggenerated Fri Dec 30 14:37:03 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_log.create_user
     *
     * @return the value of task_log.create_user
     *
     * @mbggenerated Fri Dec 30 14:37:03 CST 2016
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_log.create_user
     *
     * @param createUser the value for task_log.create_user
     *
     * @mbggenerated Fri Dec 30 14:37:03 CST 2016
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }


    @Override
    public boolean equals(Object obj) {
        return EqualsBuilder.reflectionEquals(this, obj);
    }
}