package com.medicineCenter.model.dataObject;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TaskExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public TaskExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table task
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTaskIdIsNull() {
            addCriterion("task_id is null");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNotNull() {
            addCriterion("task_id is not null");
            return (Criteria) this;
        }

        public Criteria andTaskIdEqualTo(Integer value) {
            addCriterion("task_id =", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotEqualTo(Integer value) {
            addCriterion("task_id <>", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThan(Integer value) {
            addCriterion("task_id >", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("task_id >=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThan(Integer value) {
            addCriterion("task_id <", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThanOrEqualTo(Integer value) {
            addCriterion("task_id <=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdIn(List<Integer> values) {
            addCriterion("task_id in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotIn(List<Integer> values) {
            addCriterion("task_id not in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdBetween(Integer value1, Integer value2) {
            addCriterion("task_id between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotBetween(Integer value1, Integer value2) {
            addCriterion("task_id not between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andInspectionUnitIsNull() {
            addCriterion("inspection_unit is null");
            return (Criteria) this;
        }

        public Criteria andInspectionUnitIsNotNull() {
            addCriterion("inspection_unit is not null");
            return (Criteria) this;
        }

        public Criteria andInspectionUnitEqualTo(String value) {
            addCriterion("inspection_unit =", value, "inspectionUnit");
            return (Criteria) this;
        }

        public Criteria andInspectionUnitNotEqualTo(String value) {
            addCriterion("inspection_unit <>", value, "inspectionUnit");
            return (Criteria) this;
        }

        public Criteria andInspectionUnitGreaterThan(String value) {
            addCriterion("inspection_unit >", value, "inspectionUnit");
            return (Criteria) this;
        }

        public Criteria andInspectionUnitGreaterThanOrEqualTo(String value) {
            addCriterion("inspection_unit >=", value, "inspectionUnit");
            return (Criteria) this;
        }

        public Criteria andInspectionUnitLessThan(String value) {
            addCriterion("inspection_unit <", value, "inspectionUnit");
            return (Criteria) this;
        }

        public Criteria andInspectionUnitLessThanOrEqualTo(String value) {
            addCriterion("inspection_unit <=", value, "inspectionUnit");
            return (Criteria) this;
        }

        public Criteria andInspectionUnitLike(String value) {
            addCriterion("inspection_unit like", value, "inspectionUnit");
            return (Criteria) this;
        }

        public Criteria andInspectionUnitNotLike(String value) {
            addCriterion("inspection_unit not like", value, "inspectionUnit");
            return (Criteria) this;
        }

        public Criteria andInspectionUnitIn(List<String> values) {
            addCriterion("inspection_unit in", values, "inspectionUnit");
            return (Criteria) this;
        }

        public Criteria andInspectionUnitNotIn(List<String> values) {
            addCriterion("inspection_unit not in", values, "inspectionUnit");
            return (Criteria) this;
        }

        public Criteria andInspectionUnitBetween(String value1, String value2) {
            addCriterion("inspection_unit between", value1, value2, "inspectionUnit");
            return (Criteria) this;
        }

        public Criteria andInspectionUnitNotBetween(String value1, String value2) {
            addCriterion("inspection_unit not between", value1, value2, "inspectionUnit");
            return (Criteria) this;
        }

        public Criteria andLeaderIdIsNull() {
            addCriterion("leader_id is null");
            return (Criteria) this;
        }

        public Criteria andLeaderIdIsNotNull() {
            addCriterion("leader_id is not null");
            return (Criteria) this;
        }

        public Criteria andLeaderIdEqualTo(String value) {
            addCriterion("leader_id =", value, "leaderId");
            return (Criteria) this;
        }

        public Criteria andLeaderIdNotEqualTo(String value) {
            addCriterion("leader_id <>", value, "leaderId");
            return (Criteria) this;
        }

        public Criteria andLeaderIdGreaterThan(String value) {
            addCriterion("leader_id >", value, "leaderId");
            return (Criteria) this;
        }

        public Criteria andLeaderIdGreaterThanOrEqualTo(String value) {
            addCriterion("leader_id >=", value, "leaderId");
            return (Criteria) this;
        }

        public Criteria andLeaderIdLessThan(String value) {
            addCriterion("leader_id <", value, "leaderId");
            return (Criteria) this;
        }

        public Criteria andLeaderIdLessThanOrEqualTo(String value) {
            addCriterion("leader_id <=", value, "leaderId");
            return (Criteria) this;
        }

        public Criteria andLeaderIdLike(String value) {
            addCriterion("leader_id like", value, "leaderId");
            return (Criteria) this;
        }

        public Criteria andLeaderIdNotLike(String value) {
            addCriterion("leader_id not like", value, "leaderId");
            return (Criteria) this;
        }

        public Criteria andLeaderIdIn(List<String> values) {
            addCriterion("leader_id in", values, "leaderId");
            return (Criteria) this;
        }

        public Criteria andLeaderIdNotIn(List<String> values) {
            addCriterion("leader_id not in", values, "leaderId");
            return (Criteria) this;
        }

        public Criteria andLeaderIdBetween(String value1, String value2) {
            addCriterion("leader_id between", value1, value2, "leaderId");
            return (Criteria) this;
        }

        public Criteria andLeaderIdNotBetween(String value1, String value2) {
            addCriterion("leader_id not between", value1, value2, "leaderId");
            return (Criteria) this;
        }

        public Criteria andBacteriaIsNull() {
            addCriterion("bacteria is null");
            return (Criteria) this;
        }

        public Criteria andBacteriaIsNotNull() {
            addCriterion("bacteria is not null");
            return (Criteria) this;
        }

        public Criteria andBacteriaEqualTo(String value) {
            addCriterion("bacteria =", value, "bacteria");
            return (Criteria) this;
        }

        public Criteria andBacteriaNotEqualTo(String value) {
            addCriterion("bacteria <>", value, "bacteria");
            return (Criteria) this;
        }

        public Criteria andBacteriaGreaterThan(String value) {
            addCriterion("bacteria >", value, "bacteria");
            return (Criteria) this;
        }

        public Criteria andBacteriaGreaterThanOrEqualTo(String value) {
            addCriterion("bacteria >=", value, "bacteria");
            return (Criteria) this;
        }

        public Criteria andBacteriaLessThan(String value) {
            addCriterion("bacteria <", value, "bacteria");
            return (Criteria) this;
        }

        public Criteria andBacteriaLessThanOrEqualTo(String value) {
            addCriterion("bacteria <=", value, "bacteria");
            return (Criteria) this;
        }

        public Criteria andBacteriaLike(String value) {
            addCriterion("bacteria like", value, "bacteria");
            return (Criteria) this;
        }

        public Criteria andBacteriaNotLike(String value) {
            addCriterion("bacteria not like", value, "bacteria");
            return (Criteria) this;
        }

        public Criteria andBacteriaIn(List<String> values) {
            addCriterion("bacteria in", values, "bacteria");
            return (Criteria) this;
        }

        public Criteria andBacteriaNotIn(List<String> values) {
            addCriterion("bacteria not in", values, "bacteria");
            return (Criteria) this;
        }

        public Criteria andBacteriaBetween(String value1, String value2) {
            addCriterion("bacteria between", value1, value2, "bacteria");
            return (Criteria) this;
        }

        public Criteria andBacteriaNotBetween(String value1, String value2) {
            addCriterion("bacteria not between", value1, value2, "bacteria");
            return (Criteria) this;
        }

        public Criteria andStartExecutionTimeIsNull() {
            addCriterion("start_execution_time is null");
            return (Criteria) this;
        }

        public Criteria andStartExecutionTimeIsNotNull() {
            addCriterion("start_execution_time is not null");
            return (Criteria) this;
        }

        public Criteria andStartExecutionTimeEqualTo(String value) {
            addCriterion("start_execution_time =", value, "startExecutionTime");
            return (Criteria) this;
        }

        public Criteria andStartExecutionTimeNotEqualTo(String value) {
            addCriterion("start_execution_time <>", value, "startExecutionTime");
            return (Criteria) this;
        }

        public Criteria andStartExecutionTimeGreaterThan(String value) {
            addCriterion("start_execution_time >", value, "startExecutionTime");
            return (Criteria) this;
        }

        public Criteria andStartExecutionTimeGreaterThanOrEqualTo(String value) {
            addCriterion("start_execution_time >=", value, "startExecutionTime");
            return (Criteria) this;
        }

        public Criteria andStartExecutionTimeLessThan(String value) {
            addCriterion("start_execution_time <", value, "startExecutionTime");
            return (Criteria) this;
        }

        public Criteria andStartExecutionTimeLessThanOrEqualTo(String value) {
            addCriterion("start_execution_time <=", value, "startExecutionTime");
            return (Criteria) this;
        }

        public Criteria andStartExecutionTimeLike(String value) {
            addCriterion("start_execution_time like", value, "startExecutionTime");
            return (Criteria) this;
        }

        public Criteria andStartExecutionTimeNotLike(String value) {
            addCriterion("start_execution_time not like", value, "startExecutionTime");
            return (Criteria) this;
        }

        public Criteria andStartExecutionTimeIn(List<String> values) {
            addCriterion("start_execution_time in", values, "startExecutionTime");
            return (Criteria) this;
        }

        public Criteria andStartExecutionTimeNotIn(List<String> values) {
            addCriterion("start_execution_time not in", values, "startExecutionTime");
            return (Criteria) this;
        }

        public Criteria andStartExecutionTimeBetween(String value1, String value2) {
            addCriterion("start_execution_time between", value1, value2, "startExecutionTime");
            return (Criteria) this;
        }

        public Criteria andStartExecutionTimeNotBetween(String value1, String value2) {
            addCriterion("start_execution_time not between", value1, value2, "startExecutionTime");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("state like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("state not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andSourceIsNull() {
            addCriterion("source is null");
            return (Criteria) this;
        }

        public Criteria andSourceIsNotNull() {
            addCriterion("source is not null");
            return (Criteria) this;
        }

        public Criteria andSourceEqualTo(String value) {
            addCriterion("source =", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotEqualTo(String value) {
            addCriterion("source <>", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThan(String value) {
            addCriterion("source >", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThanOrEqualTo(String value) {
            addCriterion("source >=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThan(String value) {
            addCriterion("source <", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThanOrEqualTo(String value) {
            addCriterion("source <=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLike(String value) {
            addCriterion("source like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotLike(String value) {
            addCriterion("source not like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceIn(List<String> values) {
            addCriterion("source in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotIn(List<String> values) {
            addCriterion("source not in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceBetween(String value1, String value2) {
            addCriterion("source between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotBetween(String value1, String value2) {
            addCriterion("source not between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andEndExecutionTimeIsNull() {
            addCriterion("end_execution_time is null");
            return (Criteria) this;
        }

        public Criteria andEndExecutionTimeIsNotNull() {
            addCriterion("end_execution_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndExecutionTimeEqualTo(String value) {
            addCriterion("end_execution_time =", value, "endExecutionTime");
            return (Criteria) this;
        }

        public Criteria andEndExecutionTimeNotEqualTo(String value) {
            addCriterion("end_execution_time <>", value, "endExecutionTime");
            return (Criteria) this;
        }

        public Criteria andEndExecutionTimeGreaterThan(String value) {
            addCriterion("end_execution_time >", value, "endExecutionTime");
            return (Criteria) this;
        }

        public Criteria andEndExecutionTimeGreaterThanOrEqualTo(String value) {
            addCriterion("end_execution_time >=", value, "endExecutionTime");
            return (Criteria) this;
        }

        public Criteria andEndExecutionTimeLessThan(String value) {
            addCriterion("end_execution_time <", value, "endExecutionTime");
            return (Criteria) this;
        }

        public Criteria andEndExecutionTimeLessThanOrEqualTo(String value) {
            addCriterion("end_execution_time <=", value, "endExecutionTime");
            return (Criteria) this;
        }

        public Criteria andEndExecutionTimeLike(String value) {
            addCriterion("end_execution_time like", value, "endExecutionTime");
            return (Criteria) this;
        }

        public Criteria andEndExecutionTimeNotLike(String value) {
            addCriterion("end_execution_time not like", value, "endExecutionTime");
            return (Criteria) this;
        }

        public Criteria andEndExecutionTimeIn(List<String> values) {
            addCriterion("end_execution_time in", values, "endExecutionTime");
            return (Criteria) this;
        }

        public Criteria andEndExecutionTimeNotIn(List<String> values) {
            addCriterion("end_execution_time not in", values, "endExecutionTime");
            return (Criteria) this;
        }

        public Criteria andEndExecutionTimeBetween(String value1, String value2) {
            addCriterion("end_execution_time between", value1, value2, "endExecutionTime");
            return (Criteria) this;
        }

        public Criteria andEndExecutionTimeNotBetween(String value1, String value2) {
            addCriterion("end_execution_time not between", value1, value2, "endExecutionTime");
            return (Criteria) this;
        }

        public Criteria andAttributionIsNull() {
            addCriterion("attribution is null");
            return (Criteria) this;
        }

        public Criteria andAttributionIsNotNull() {
            addCriterion("attribution is not null");
            return (Criteria) this;
        }

        public Criteria andAttributionEqualTo(String value) {
            addCriterion("attribution =", value, "attribution");
            return (Criteria) this;
        }

        public Criteria andAttributionNotEqualTo(String value) {
            addCriterion("attribution <>", value, "attribution");
            return (Criteria) this;
        }

        public Criteria andAttributionGreaterThan(String value) {
            addCriterion("attribution >", value, "attribution");
            return (Criteria) this;
        }

        public Criteria andAttributionGreaterThanOrEqualTo(String value) {
            addCriterion("attribution >=", value, "attribution");
            return (Criteria) this;
        }

        public Criteria andAttributionLessThan(String value) {
            addCriterion("attribution <", value, "attribution");
            return (Criteria) this;
        }

        public Criteria andAttributionLessThanOrEqualTo(String value) {
            addCriterion("attribution <=", value, "attribution");
            return (Criteria) this;
        }

        public Criteria andAttributionLike(String value) {
            addCriterion("attribution like", value, "attribution");
            return (Criteria) this;
        }

        public Criteria andAttributionNotLike(String value) {
            addCriterion("attribution not like", value, "attribution");
            return (Criteria) this;
        }

        public Criteria andAttributionIn(List<String> values) {
            addCriterion("attribution in", values, "attribution");
            return (Criteria) this;
        }

        public Criteria andAttributionNotIn(List<String> values) {
            addCriterion("attribution not in", values, "attribution");
            return (Criteria) this;
        }

        public Criteria andAttributionBetween(String value1, String value2) {
            addCriterion("attribution between", value1, value2, "attribution");
            return (Criteria) this;
        }

        public Criteria andAttributionNotBetween(String value1, String value2) {
            addCriterion("attribution not between", value1, value2, "attribution");
            return (Criteria) this;
        }

        public Criteria andChecktypeIsNull() {
            addCriterion("checktype is null");
            return (Criteria) this;
        }

        public Criteria andChecktypeIsNotNull() {
            addCriterion("checktype is not null");
            return (Criteria) this;
        }

        public Criteria andChecktypeEqualTo(String value) {
            addCriterion("checktype =", value, "checktype");
            return (Criteria) this;
        }

        public Criteria andChecktypeNotEqualTo(String value) {
            addCriterion("checktype <>", value, "checktype");
            return (Criteria) this;
        }

        public Criteria andChecktypeGreaterThan(String value) {
            addCriterion("checktype >", value, "checktype");
            return (Criteria) this;
        }

        public Criteria andChecktypeGreaterThanOrEqualTo(String value) {
            addCriterion("checktype >=", value, "checktype");
            return (Criteria) this;
        }

        public Criteria andChecktypeLessThan(String value) {
            addCriterion("checktype <", value, "checktype");
            return (Criteria) this;
        }

        public Criteria andChecktypeLessThanOrEqualTo(String value) {
            addCriterion("checktype <=", value, "checktype");
            return (Criteria) this;
        }

        public Criteria andChecktypeLike(String value) {
            addCriterion("checktype like", value, "checktype");
            return (Criteria) this;
        }

        public Criteria andChecktypeNotLike(String value) {
            addCriterion("checktype not like", value, "checktype");
            return (Criteria) this;
        }

        public Criteria andChecktypeIn(List<String> values) {
            addCriterion("checktype in", values, "checktype");
            return (Criteria) this;
        }

        public Criteria andChecktypeNotIn(List<String> values) {
            addCriterion("checktype not in", values, "checktype");
            return (Criteria) this;
        }

        public Criteria andChecktypeBetween(String value1, String value2) {
            addCriterion("checktype between", value1, value2, "checktype");
            return (Criteria) this;
        }

        public Criteria andChecktypeNotBetween(String value1, String value2) {
            addCriterion("checktype not between", value1, value2, "checktype");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table task
     *
     * @mbggenerated do_not_delete_during_merge Tue Feb 14 16:43:38 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table task
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}