package com.medicineCenter.model.dataObject;

import java.util.ArrayList;
import java.util.List;

public class TaskInspectionInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task_inspection_info
     *
     * @mbggenerated Thu Feb 23 14:28:40 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task_inspection_info
     *
     * @mbggenerated Thu Feb 23 14:28:40 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task_inspection_info
     *
     * @mbggenerated Thu Feb 23 14:28:40 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_inspection_info
     *
     * @mbggenerated Thu Feb 23 14:28:40 CST 2017
     */
    public TaskInspectionInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_inspection_info
     *
     * @mbggenerated Thu Feb 23 14:28:40 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_inspection_info
     *
     * @mbggenerated Thu Feb 23 14:28:40 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_inspection_info
     *
     * @mbggenerated Thu Feb 23 14:28:40 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_inspection_info
     *
     * @mbggenerated Thu Feb 23 14:28:40 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_inspection_info
     *
     * @mbggenerated Thu Feb 23 14:28:40 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_inspection_info
     *
     * @mbggenerated Thu Feb 23 14:28:40 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_inspection_info
     *
     * @mbggenerated Thu Feb 23 14:28:40 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_inspection_info
     *
     * @mbggenerated Thu Feb 23 14:28:40 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_inspection_info
     *
     * @mbggenerated Thu Feb 23 14:28:40 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_inspection_info
     *
     * @mbggenerated Thu Feb 23 14:28:40 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table task_inspection_info
     *
     * @mbggenerated Thu Feb 23 14:28:40 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNull() {
            addCriterion("task_id is null");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNotNull() {
            addCriterion("task_id is not null");
            return (Criteria) this;
        }

        public Criteria andTaskIdEqualTo(Integer value) {
            addCriterion("task_id =", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotEqualTo(Integer value) {
            addCriterion("task_id <>", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThan(Integer value) {
            addCriterion("task_id >", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("task_id >=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThan(Integer value) {
            addCriterion("task_id <", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThanOrEqualTo(Integer value) {
            addCriterion("task_id <=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdIn(List<Integer> values) {
            addCriterion("task_id in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotIn(List<Integer> values) {
            addCriterion("task_id not in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdBetween(Integer value1, Integer value2) {
            addCriterion("task_id between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotBetween(Integer value1, Integer value2) {
            addCriterion("task_id not between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andInspectionUnitIsNull() {
            addCriterion("inspection_unit is null");
            return (Criteria) this;
        }

        public Criteria andInspectionUnitIsNotNull() {
            addCriterion("inspection_unit is not null");
            return (Criteria) this;
        }

        public Criteria andInspectionUnitEqualTo(String value) {
            addCriterion("inspection_unit =", value, "inspectionUnit");
            return (Criteria) this;
        }

        public Criteria andInspectionUnitNotEqualTo(String value) {
            addCriterion("inspection_unit <>", value, "inspectionUnit");
            return (Criteria) this;
        }

        public Criteria andInspectionUnitGreaterThan(String value) {
            addCriterion("inspection_unit >", value, "inspectionUnit");
            return (Criteria) this;
        }

        public Criteria andInspectionUnitGreaterThanOrEqualTo(String value) {
            addCriterion("inspection_unit >=", value, "inspectionUnit");
            return (Criteria) this;
        }

        public Criteria andInspectionUnitLessThan(String value) {
            addCriterion("inspection_unit <", value, "inspectionUnit");
            return (Criteria) this;
        }

        public Criteria andInspectionUnitLessThanOrEqualTo(String value) {
            addCriterion("inspection_unit <=", value, "inspectionUnit");
            return (Criteria) this;
        }

        public Criteria andInspectionUnitLike(String value) {
            addCriterion("inspection_unit like", value, "inspectionUnit");
            return (Criteria) this;
        }

        public Criteria andInspectionUnitNotLike(String value) {
            addCriterion("inspection_unit not like", value, "inspectionUnit");
            return (Criteria) this;
        }

        public Criteria andInspectionUnitIn(List<String> values) {
            addCriterion("inspection_unit in", values, "inspectionUnit");
            return (Criteria) this;
        }

        public Criteria andInspectionUnitNotIn(List<String> values) {
            addCriterion("inspection_unit not in", values, "inspectionUnit");
            return (Criteria) this;
        }

        public Criteria andInspectionUnitBetween(String value1, String value2) {
            addCriterion("inspection_unit between", value1, value2, "inspectionUnit");
            return (Criteria) this;
        }

        public Criteria andInspectionUnitNotBetween(String value1, String value2) {
            addCriterion("inspection_unit not between", value1, value2, "inspectionUnit");
            return (Criteria) this;
        }

        public Criteria andAttributionIsNull() {
            addCriterion("attribution is null");
            return (Criteria) this;
        }

        public Criteria andAttributionIsNotNull() {
            addCriterion("attribution is not null");
            return (Criteria) this;
        }

        public Criteria andAttributionEqualTo(String value) {
            addCriterion("attribution =", value, "attribution");
            return (Criteria) this;
        }

        public Criteria andAttributionNotEqualTo(String value) {
            addCriterion("attribution <>", value, "attribution");
            return (Criteria) this;
        }

        public Criteria andAttributionGreaterThan(String value) {
            addCriterion("attribution >", value, "attribution");
            return (Criteria) this;
        }

        public Criteria andAttributionGreaterThanOrEqualTo(String value) {
            addCriterion("attribution >=", value, "attribution");
            return (Criteria) this;
        }

        public Criteria andAttributionLessThan(String value) {
            addCriterion("attribution <", value, "attribution");
            return (Criteria) this;
        }

        public Criteria andAttributionLessThanOrEqualTo(String value) {
            addCriterion("attribution <=", value, "attribution");
            return (Criteria) this;
        }

        public Criteria andAttributionLike(String value) {
            addCriterion("attribution like", value, "attribution");
            return (Criteria) this;
        }

        public Criteria andAttributionNotLike(String value) {
            addCriterion("attribution not like", value, "attribution");
            return (Criteria) this;
        }

        public Criteria andAttributionIn(List<String> values) {
            addCriterion("attribution in", values, "attribution");
            return (Criteria) this;
        }

        public Criteria andAttributionNotIn(List<String> values) {
            addCriterion("attribution not in", values, "attribution");
            return (Criteria) this;
        }

        public Criteria andAttributionBetween(String value1, String value2) {
            addCriterion("attribution between", value1, value2, "attribution");
            return (Criteria) this;
        }

        public Criteria andAttributionNotBetween(String value1, String value2) {
            addCriterion("attribution not between", value1, value2, "attribution");
            return (Criteria) this;
        }

        public Criteria andChecktypeIsNull() {
            addCriterion("checktype is null");
            return (Criteria) this;
        }

        public Criteria andChecktypeIsNotNull() {
            addCriterion("checktype is not null");
            return (Criteria) this;
        }

        public Criteria andChecktypeEqualTo(String value) {
            addCriterion("checktype =", value, "checktype");
            return (Criteria) this;
        }

        public Criteria andChecktypeNotEqualTo(String value) {
            addCriterion("checktype <>", value, "checktype");
            return (Criteria) this;
        }

        public Criteria andChecktypeGreaterThan(String value) {
            addCriterion("checktype >", value, "checktype");
            return (Criteria) this;
        }

        public Criteria andChecktypeGreaterThanOrEqualTo(String value) {
            addCriterion("checktype >=", value, "checktype");
            return (Criteria) this;
        }

        public Criteria andChecktypeLessThan(String value) {
            addCriterion("checktype <", value, "checktype");
            return (Criteria) this;
        }

        public Criteria andChecktypeLessThanOrEqualTo(String value) {
            addCriterion("checktype <=", value, "checktype");
            return (Criteria) this;
        }

        public Criteria andChecktypeLike(String value) {
            addCriterion("checktype like", value, "checktype");
            return (Criteria) this;
        }

        public Criteria andChecktypeNotLike(String value) {
            addCriterion("checktype not like", value, "checktype");
            return (Criteria) this;
        }

        public Criteria andChecktypeIn(List<String> values) {
            addCriterion("checktype in", values, "checktype");
            return (Criteria) this;
        }

        public Criteria andChecktypeNotIn(List<String> values) {
            addCriterion("checktype not in", values, "checktype");
            return (Criteria) this;
        }

        public Criteria andChecktypeBetween(String value1, String value2) {
            addCriterion("checktype between", value1, value2, "checktype");
            return (Criteria) this;
        }

        public Criteria andChecktypeNotBetween(String value1, String value2) {
            addCriterion("checktype not between", value1, value2, "checktype");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table task_inspection_info
     *
     * @mbggenerated do_not_delete_during_merge Thu Feb 23 14:28:40 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table task_inspection_info
     *
     * @mbggenerated Thu Feb 23 14:28:40 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}