package com.medicineCenter.model.dataObject;

import org.apache.commons.lang.builder.EqualsBuilder;

import java.util.Date;

public class Task {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_id
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    private Integer taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.inspection_unit
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    private String inspectionUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.leader_id
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    private String leaderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.bacteria
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    private String bacteria;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.start_execution_time
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    private String startExecutionTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.state
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.source
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.create_user
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.create_time
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.end_execution_time
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    private String endExecutionTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.attribution
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    private String attribution;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.checktype
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    private String checktype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_id
     *
     * @return the value of task.task_id
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_id
     *
     * @param taskId the value for task.task_id
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.inspection_unit
     *
     * @return the value of task.inspection_unit
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public String getInspectionUnit() {
        return inspectionUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.inspection_unit
     *
     * @param inspectionUnit the value for task.inspection_unit
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public void setInspectionUnit(String inspectionUnit) {
        this.inspectionUnit = inspectionUnit == null ? null : inspectionUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.leader_id
     *
     * @return the value of task.leader_id
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public String getLeaderId() {
        return leaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.leader_id
     *
     * @param leaderId the value for task.leader_id
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public void setLeaderId(String leaderId) {
        this.leaderId = leaderId == null ? null : leaderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.bacteria
     *
     * @return the value of task.bacteria
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public String getBacteria() {
        return bacteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.bacteria
     *
     * @param bacteria the value for task.bacteria
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public void setBacteria(String bacteria) {
        this.bacteria = bacteria == null ? null : bacteria.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.start_execution_time
     *
     * @return the value of task.start_execution_time
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public String getStartExecutionTime() {
        return startExecutionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.start_execution_time
     *
     * @param startExecutionTime the value for task.start_execution_time
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public void setStartExecutionTime(String startExecutionTime) {
        this.startExecutionTime = startExecutionTime == null ? null : startExecutionTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.state
     *
     * @return the value of task.state
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.state
     *
     * @param state the value for task.state
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.source
     *
     * @return the value of task.source
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.source
     *
     * @param source the value for task.source
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.create_user
     *
     * @return the value of task.create_user
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.create_user
     *
     * @param createUser the value for task.create_user
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.create_time
     *
     * @return the value of task.create_time
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.create_time
     *
     * @param createTime the value for task.create_time
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.end_execution_time
     *
     * @return the value of task.end_execution_time
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public String getEndExecutionTime() {
        return endExecutionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.end_execution_time
     *
     * @param endExecutionTime the value for task.end_execution_time
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public void setEndExecutionTime(String endExecutionTime) {
        this.endExecutionTime = endExecutionTime == null ? null : endExecutionTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.attribution
     *
     * @return the value of task.attribution
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public String getAttribution() {
        return attribution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.attribution
     *
     * @param attribution the value for task.attribution
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public void setAttribution(String attribution) {
        this.attribution = attribution == null ? null : attribution.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.checktype
     *
     * @return the value of task.checktype
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public String getChecktype() {
        return checktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.checktype
     *
     * @param checktype the value for task.checktype
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public void setChecktype(String checktype) {
        this.checktype = checktype == null ? null : checktype.trim();
    }

    @Override
    public boolean equals(Object obj) {
        return EqualsBuilder.reflectionEquals(this, obj);
    }
}