package com.medicineCenter.model.dto;

import java.util.Date;

public class ExpertsDTO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experts.experts_id
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    private Integer expertsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experts.name
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experts.gender
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experts.age
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    private String age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experts.school
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    private String school;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experts.degree
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    private String degree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experts.work
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    private String work;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experts.title
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experts.phone
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experts.remarks
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experts.leader
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    private String leader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experts.bacteria
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    private String bacteria;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experts.category
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experts.category_two
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    private String categoryTwo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experts.source
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experts.CREATE_TIME
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    private Date createTime;
    private String state;
    private String reason;
    private String attribution;

    public String getAttribution() {
        return attribution;
    }

    public void setAttribution(String attribution) {
        this.attribution = attribution;
    }

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experts.experts_id
     *
     * @return the value of experts.experts_id
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    public Integer getExpertsId() {
        return expertsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experts.experts_id
     *
     * @param expertsId the value for experts.experts_id
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    public void setExpertsId(Integer expertsId) {
        this.expertsId = expertsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experts.name
     *
     * @return the value of experts.name
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experts.name
     *
     * @param name the value for experts.name
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experts.gender
     *
     * @return the value of experts.gender
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experts.gender
     *
     * @param gender the value for experts.gender
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experts.age
     *
     * @return the value of experts.age
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experts.age
     *
     * @param age the value for experts.age
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    public void setAge(String age) {
        this.age = age == null ? null : age.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experts.school
     *
     * @return the value of experts.school
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experts.school
     *
     * @param school the value for experts.school
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experts.degree
     *
     * @return the value of experts.degree
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    public String getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experts.degree
     *
     * @param degree the value for experts.degree
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    public void setDegree(String degree) {
        this.degree = degree == null ? null : degree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experts.work
     *
     * @return the value of experts.work
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    public String getWork() {
        return work;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experts.work
     *
     * @param work the value for experts.work
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    public void setWork(String work) {
        this.work = work == null ? null : work.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experts.title
     *
     * @return the value of experts.title
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experts.title
     *
     * @param title the value for experts.title
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experts.phone
     *
     * @return the value of experts.phone
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experts.phone
     *
     * @param phone the value for experts.phone
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experts.remarks
     *
     * @return the value of experts.remarks
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experts.remarks
     *
     * @param remarks the value for experts.remarks
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experts.leader
     *
     * @return the value of experts.leader
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    public String getLeader() {
        return leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experts.leader
     *
     * @param leader the value for experts.leader
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    public void setLeader(String leader) {
        this.leader = leader == null ? null : leader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experts.bacteria
     *
     * @return the value of experts.bacteria
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    public String getBacteria() {
        return bacteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experts.bacteria
     *
     * @param bacteria the value for experts.bacteria
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    public void setBacteria(String bacteria) {
        this.bacteria = bacteria == null ? null : bacteria.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experts.category
     *
     * @return the value of experts.category
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    public String getCategory() {
        return category;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experts.category
     *
     * @param category the value for experts.category
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experts.category_two
     *
     * @return the value of experts.category_two
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    public String getCategoryTwo() {
        return categoryTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experts.category_two
     *
     * @param categoryTwo the value for experts.category_two
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    public void setCategoryTwo(String categoryTwo) {
        this.categoryTwo = categoryTwo == null ? null : categoryTwo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experts.source
     *
     * @return the value of experts.source
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experts.source
     *
     * @param source the value for experts.source
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experts.CREATE_TIME
     *
     * @return the value of experts.CREATE_TIME
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experts.CREATE_TIME
     *
     * @param createTime the value for experts.CREATE_TIME
     *
     * @mbggenerated Tue Oct 25 10:12:11 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}