package com.medicineCenter.dao;

import com.medicineCenter.model.dataObject.ExpertsUpLog;
import com.medicineCenter.model.dataObject.ExpertsUpLogExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface ExpertsUpLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts_up_log
     *
     * @mbggenerated Sun Jun 11 21:49:49 CST 2017
     */
    @SelectProvider(type=ExpertsUpLogSqlProvider.class, method="countByExample")
    int countByExample(ExpertsUpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts_up_log
     *
     * @mbggenerated Sun Jun 11 21:49:49 CST 2017
     */
    @DeleteProvider(type=ExpertsUpLogSqlProvider.class, method="deleteByExample")
    int deleteByExample(ExpertsUpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts_up_log
     *
     * @mbggenerated Sun Jun 11 21:49:49 CST 2017
     */
    @Delete({
        "delete from experts_up_log",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts_up_log
     *
     * @mbggenerated Sun Jun 11 21:49:49 CST 2017
     */
    @Insert({
        "insert into experts_up_log (id, experts_id, ",
        "upadte_details, source, ",
        "CREATE_TIME, user, ",
        "type)",
        "values (#{id,jdbcType=INTEGER}, #{expertsId,jdbcType=INTEGER}, ",
        "#{upadteDetails,jdbcType=VARCHAR}, #{source,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{user,jdbcType=VARCHAR}, ",
        "#{type,jdbcType=VARCHAR})"
    })
    int insert(ExpertsUpLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts_up_log
     *
     * @mbggenerated Sun Jun 11 21:49:49 CST 2017
     */
    @InsertProvider(type=ExpertsUpLogSqlProvider.class, method="insertSelective")
    int insertSelective(ExpertsUpLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts_up_log
     *
     * @mbggenerated Sun Jun 11 21:49:49 CST 2017
     */
    @SelectProvider(type=ExpertsUpLogSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="experts_id", property="expertsId", jdbcType=JdbcType.INTEGER),
        @Result(column="upadte_details", property="upadteDetails", jdbcType=JdbcType.VARCHAR),
        @Result(column="source", property="source", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="user", property="user", jdbcType=JdbcType.VARCHAR),
        @Result(column="type", property="type", jdbcType=JdbcType.VARCHAR)
    })
    List<ExpertsUpLog> selectByExample(ExpertsUpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts_up_log
     *
     * @mbggenerated Sun Jun 11 21:49:49 CST 2017
     */
    @Select({
        "select",
        "id, experts_id, upadte_details, source, CREATE_TIME, user, type",
        "from experts_up_log",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="experts_id", property="expertsId", jdbcType=JdbcType.INTEGER),
        @Result(column="upadte_details", property="upadteDetails", jdbcType=JdbcType.VARCHAR),
        @Result(column="source", property="source", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="user", property="user", jdbcType=JdbcType.VARCHAR),
        @Result(column="type", property="type", jdbcType=JdbcType.VARCHAR)
    })
    ExpertsUpLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts_up_log
     *
     * @mbggenerated Sun Jun 11 21:49:49 CST 2017
     */
    @UpdateProvider(type=ExpertsUpLogSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ExpertsUpLog record, @Param("example") ExpertsUpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts_up_log
     *
     * @mbggenerated Sun Jun 11 21:49:49 CST 2017
     */
    @UpdateProvider(type=ExpertsUpLogSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ExpertsUpLog record, @Param("example") ExpertsUpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts_up_log
     *
     * @mbggenerated Sun Jun 11 21:49:49 CST 2017
     */
    @UpdateProvider(type=ExpertsUpLogSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ExpertsUpLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts_up_log
     *
     * @mbggenerated Sun Jun 11 21:49:49 CST 2017
     */
    @Update({
        "update experts_up_log",
        "set experts_id = #{expertsId,jdbcType=INTEGER},",
          "upadte_details = #{upadteDetails,jdbcType=VARCHAR},",
          "source = #{source,jdbcType=VARCHAR},",
          "CREATE_TIME = #{createTime,jdbcType=TIMESTAMP},",
          "user = #{user,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ExpertsUpLog record);
}