package com.medicineCenter.dao;

import com.medicineCenter.model.dataObject.Experts;
import com.medicineCenter.model.dataObject.ExpertsExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface ExpertsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts
     *
     * @mbggenerated Wed Dec 14 14:21:08 CST 2016
     */
    @SelectProvider(type=ExpertsSqlProvider.class, method="countByExample")
    int countByExample(ExpertsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts
     *
     * @mbggenerated Wed Dec 14 14:21:08 CST 2016
     */
    @DeleteProvider(type=ExpertsSqlProvider.class, method="deleteByExample")
    int deleteByExample(ExpertsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts
     *
     * @mbggenerated Wed Dec 14 14:21:08 CST 2016
     */
    @Delete({
            "delete from experts",
            "where experts_id = #{expertsId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer expertsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts
     *
     * @mbggenerated Wed Dec 14 14:21:08 CST 2016
     */
    @Insert({
            "insert into experts (experts_id, name, ",
            "gender, age, school, ",
            "degree, work, title, ",
            "phone, remarks, ",
            "leader, bacteria, ",
            "category, category_two, ",
            "source, CREATE_TIME, ",
            "attribution)",
            "values (#{expertsId,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
            "#{gender,jdbcType=VARCHAR}, #{age,jdbcType=VARCHAR}, #{school,jdbcType=VARCHAR}, ",
            "#{degree,jdbcType=VARCHAR}, #{work,jdbcType=VARCHAR}, #{title,jdbcType=VARCHAR}, ",
            "#{phone,jdbcType=VARCHAR}, #{remarks,jdbcType=VARCHAR}, ",
            "#{leader,jdbcType=VARCHAR}, #{bacteria,jdbcType=VARCHAR}, ",
            "#{category,jdbcType=VARCHAR}, #{categoryTwo,jdbcType=VARCHAR}, ",
            "#{source,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
            "#{attribution,jdbcType=VARCHAR})"
    })
    int insert(Experts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts
     *
     * @mbggenerated Wed Dec 14 14:21:08 CST 2016
     */
    @InsertProvider(type=ExpertsSqlProvider.class, method="insertSelective")
    int insertSelective(Experts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts
     *
     * @mbggenerated Wed Dec 14 14:21:08 CST 2016
     */
    @SelectProvider(type=ExpertsSqlProvider.class, method="selectByExample")
    @Results({
            @Result(column="experts_id", property="expertsId", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
            @Result(column="gender", property="gender", jdbcType=JdbcType.VARCHAR),
            @Result(column="age", property="age", jdbcType=JdbcType.VARCHAR),
            @Result(column="school", property="school", jdbcType=JdbcType.VARCHAR),
            @Result(column="degree", property="degree", jdbcType=JdbcType.VARCHAR),
            @Result(column="work", property="work", jdbcType=JdbcType.VARCHAR),
            @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
            @Result(column="phone", property="phone", jdbcType=JdbcType.VARCHAR),
            @Result(column="remarks", property="remarks", jdbcType=JdbcType.VARCHAR),
            @Result(column="leader", property="leader", jdbcType=JdbcType.VARCHAR),
            @Result(column="bacteria", property="bacteria", jdbcType=JdbcType.VARCHAR),
            @Result(column="category", property="category", jdbcType=JdbcType.VARCHAR),
            @Result(column="category_two", property="categoryTwo", jdbcType=JdbcType.VARCHAR),
            @Result(column="source", property="source", jdbcType=JdbcType.VARCHAR),
            @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="attribution", property="attribution", jdbcType=JdbcType.VARCHAR)
    })
    List<Experts> selectByExample(ExpertsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts
     *
     * @mbggenerated Wed Dec 14 14:21:08 CST 2016
     */
    @Select({
            "select",
            "experts_id, name, gender, age, school, degree, work, title, phone, remarks, ",
            "leader, bacteria, category, category_two, source, CREATE_TIME, attribution",
            "from experts",
            "where experts_id = #{expertsId,jdbcType=INTEGER}"
    })
    @Results({
            @Result(column="experts_id", property="expertsId", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
            @Result(column="gender", property="gender", jdbcType=JdbcType.VARCHAR),
            @Result(column="age", property="age", jdbcType=JdbcType.VARCHAR),
            @Result(column="school", property="school", jdbcType=JdbcType.VARCHAR),
            @Result(column="degree", property="degree", jdbcType=JdbcType.VARCHAR),
            @Result(column="work", property="work", jdbcType=JdbcType.VARCHAR),
            @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
            @Result(column="phone", property="phone", jdbcType=JdbcType.VARCHAR),
            @Result(column="remarks", property="remarks", jdbcType=JdbcType.VARCHAR),
            @Result(column="leader", property="leader", jdbcType=JdbcType.VARCHAR),
            @Result(column="bacteria", property="bacteria", jdbcType=JdbcType.VARCHAR),
            @Result(column="category", property="category", jdbcType=JdbcType.VARCHAR),
            @Result(column="category_two", property="categoryTwo", jdbcType=JdbcType.VARCHAR),
            @Result(column="source", property="source", jdbcType=JdbcType.VARCHAR),
            @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="attribution", property="attribution", jdbcType=JdbcType.VARCHAR)
    })
    Experts selectByPrimaryKey(Integer expertsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts
     *
     * @mbggenerated Wed Dec 14 14:21:08 CST 2016
     */
    @UpdateProvider(type=ExpertsSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Experts record, @Param("example") ExpertsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts
     *
     * @mbggenerated Wed Dec 14 14:21:08 CST 2016
     */
    @UpdateProvider(type=ExpertsSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Experts record, @Param("example") ExpertsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts
     *
     * @mbggenerated Wed Dec 14 14:21:08 CST 2016
     */
    @UpdateProvider(type=ExpertsSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Experts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts
     *
     * @mbggenerated Wed Dec 14 14:21:08 CST 2016
     */
    @Update({
            "update experts",
            "set name = #{name,jdbcType=VARCHAR},",
            "gender = #{gender,jdbcType=VARCHAR},",
            "age = #{age,jdbcType=VARCHAR},",
            "school = #{school,jdbcType=VARCHAR},",
            "degree = #{degree,jdbcType=VARCHAR},",
            "work = #{work,jdbcType=VARCHAR},",
            "title = #{title,jdbcType=VARCHAR},",
            "phone = #{phone,jdbcType=VARCHAR},",
            "remarks = #{remarks,jdbcType=VARCHAR},",
            "leader = #{leader,jdbcType=VARCHAR},",
            "bacteria = #{bacteria,jdbcType=VARCHAR},",
            "category = #{category,jdbcType=VARCHAR},",
            "category_two = #{categoryTwo,jdbcType=VARCHAR},",
            "source = #{source,jdbcType=VARCHAR},",
            "CREATE_TIME = #{createTime,jdbcType=TIMESTAMP},",
            "attribution = #{attribution,jdbcType=VARCHAR}",
            "where experts_id = #{expertsId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Experts record);
}