package com.medicineCenter.dao;

import com.medicineCenter.model.dataObject.ExpertsUpLog;
import com.medicineCenter.model.dataObject.ExpertsUpLogExample;
import com.medicineCenter.model.dataObject.ExpertsUpLogExample.Criteria;
import com.medicineCenter.model.dataObject.ExpertsUpLogExample.Criterion;
import org.apache.ibatis.jdbc.SQL;

import java.util.List;
import java.util.Map;

public class ExpertsUpLogSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts_up_log
     *
     * @mbggenerated Sun Jun 11 21:49:49 CST 2017
     */
    public String countByExample(ExpertsUpLogExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("experts_up_log");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts_up_log
     *
     * @mbggenerated Sun Jun 11 21:49:49 CST 2017
     */
    public String deleteByExample(ExpertsUpLogExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("experts_up_log");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts_up_log
     *
     * @mbggenerated Sun Jun 11 21:49:49 CST 2017
     */
    public String insertSelective(ExpertsUpLog record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("experts_up_log");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getExpertsId() != null) {
            sql.VALUES("experts_id", "#{expertsId,jdbcType=INTEGER}");
        }
        
        if (record.getUpadteDetails() != null) {
            sql.VALUES("upadte_details", "#{upadteDetails,jdbcType=VARCHAR}");
        }
        
        if (record.getSource() != null) {
            sql.VALUES("source", "#{source,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("CREATE_TIME", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUser() != null) {
            sql.VALUES("user", "#{user,jdbcType=VARCHAR}");
        }
        
        if (record.getType() != null) {
            sql.VALUES("type", "#{type,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts_up_log
     *
     * @mbggenerated Sun Jun 11 21:49:49 CST 2017
     */
    public String selectByExample(ExpertsUpLogExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("experts_id");
        sql.SELECT("upadte_details");
        sql.SELECT("source");
        sql.SELECT("CREATE_TIME");
        sql.SELECT("user");
        sql.SELECT("type");
        sql.FROM("experts_up_log");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts_up_log
     *
     * @mbggenerated Sun Jun 11 21:49:49 CST 2017
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        ExpertsUpLog record = (ExpertsUpLog) parameter.get("record");
        ExpertsUpLogExample example = (ExpertsUpLogExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("experts_up_log");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getExpertsId() != null) {
            sql.SET("experts_id = #{record.expertsId,jdbcType=INTEGER}");
        }
        
        if (record.getUpadteDetails() != null) {
            sql.SET("upadte_details = #{record.upadteDetails,jdbcType=VARCHAR}");
        }
        
        if (record.getSource() != null) {
            sql.SET("source = #{record.source,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("CREATE_TIME = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUser() != null) {
            sql.SET("user = #{record.user,jdbcType=VARCHAR}");
        }
        
        if (record.getType() != null) {
            sql.SET("type = #{record.type,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts_up_log
     *
     * @mbggenerated Sun Jun 11 21:49:49 CST 2017
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("experts_up_log");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("experts_id = #{record.expertsId,jdbcType=INTEGER}");
        sql.SET("upadte_details = #{record.upadteDetails,jdbcType=VARCHAR}");
        sql.SET("source = #{record.source,jdbcType=VARCHAR}");
        sql.SET("CREATE_TIME = #{record.createTime,jdbcType=TIMESTAMP}");
        sql.SET("user = #{record.user,jdbcType=VARCHAR}");
        sql.SET("type = #{record.type,jdbcType=VARCHAR}");
        
        ExpertsUpLogExample example = (ExpertsUpLogExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts_up_log
     *
     * @mbggenerated Sun Jun 11 21:49:49 CST 2017
     */
    public String updateByPrimaryKeySelective(ExpertsUpLog record) {
        SQL sql = new SQL();
        sql.UPDATE("experts_up_log");
        
        if (record.getExpertsId() != null) {
            sql.SET("experts_id = #{expertsId,jdbcType=INTEGER}");
        }
        
        if (record.getUpadteDetails() != null) {
            sql.SET("upadte_details = #{upadteDetails,jdbcType=VARCHAR}");
        }
        
        if (record.getSource() != null) {
            sql.SET("source = #{source,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("CREATE_TIME = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUser() != null) {
            sql.SET("user = #{user,jdbcType=VARCHAR}");
        }
        
        if (record.getType() != null) {
            sql.SET("type = #{type,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts_up_log
     *
     * @mbggenerated Sun Jun 11 21:49:49 CST 2017
     */
    protected void applyWhere(SQL sql, ExpertsUpLogExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}