package com.medicineCenter.dao;

import com.medicineCenter.model.dataObject.ExpertsCdLog;
import com.medicineCenter.model.dataObject.ExpertsCdLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ExpertsCdLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts_cd_log
     *
     * @mbggenerated Sun Jun 11 21:49:49 CST 2017
     */
    @SelectProvider(type=ExpertsCdLogSqlProvider.class, method="countByExample")
    int countByExample(ExpertsCdLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts_cd_log
     *
     * @mbggenerated Sun Jun 11 21:49:49 CST 2017
     */
    @DeleteProvider(type=ExpertsCdLogSqlProvider.class, method="deleteByExample")
    int deleteByExample(ExpertsCdLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts_cd_log
     *
     * @mbggenerated Sun Jun 11 21:49:49 CST 2017
     */
    @Delete({
        "delete from experts_cd_log",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts_cd_log
     *
     * @mbggenerated Sun Jun 11 21:49:49 CST 2017
     */
    @Insert({
        "insert into experts_cd_log (id, experts_id, ",
        "name, gender, age, ",
        "school, degree, ",
        "work, title, phone, ",
        "remarks, leader, ",
        "bacteria, category, ",
        "category_two, category_three, ",
        "source, attribution, ",
        "CREATE_TIME, user, ",
        "type)",
        "values (#{id,jdbcType=INTEGER}, #{expertsId,jdbcType=INTEGER}, ",
        "#{name,jdbcType=VARCHAR}, #{gender,jdbcType=VARCHAR}, #{age,jdbcType=VARCHAR}, ",
        "#{school,jdbcType=VARCHAR}, #{degree,jdbcType=VARCHAR}, ",
        "#{work,jdbcType=VARCHAR}, #{title,jdbcType=VARCHAR}, #{phone,jdbcType=VARCHAR}, ",
        "#{remarks,jdbcType=VARCHAR}, #{leader,jdbcType=VARCHAR}, ",
        "#{bacteria,jdbcType=VARCHAR}, #{category,jdbcType=VARCHAR}, ",
        "#{categoryTwo,jdbcType=VARCHAR}, #{categoryThree,jdbcType=VARCHAR}, ",
        "#{source,jdbcType=VARCHAR}, #{attribution,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{user,jdbcType=VARCHAR}, ",
        "#{type,jdbcType=VARCHAR})"
    })
    int insert(ExpertsCdLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts_cd_log
     *
     * @mbggenerated Sun Jun 11 21:49:49 CST 2017
     */
    @InsertProvider(type=ExpertsCdLogSqlProvider.class, method="insertSelective")
    int insertSelective(ExpertsCdLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts_cd_log
     *
     * @mbggenerated Sun Jun 11 21:49:49 CST 2017
     */
    @SelectProvider(type=ExpertsCdLogSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="experts_id", property="expertsId", jdbcType=JdbcType.INTEGER),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="gender", property="gender", jdbcType=JdbcType.VARCHAR),
        @Result(column="age", property="age", jdbcType=JdbcType.VARCHAR),
        @Result(column="school", property="school", jdbcType=JdbcType.VARCHAR),
        @Result(column="degree", property="degree", jdbcType=JdbcType.VARCHAR),
        @Result(column="work", property="work", jdbcType=JdbcType.VARCHAR),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="phone", property="phone", jdbcType=JdbcType.VARCHAR),
        @Result(column="remarks", property="remarks", jdbcType=JdbcType.VARCHAR),
        @Result(column="leader", property="leader", jdbcType=JdbcType.VARCHAR),
        @Result(column="bacteria", property="bacteria", jdbcType=JdbcType.VARCHAR),
        @Result(column="category", property="category", jdbcType=JdbcType.VARCHAR),
        @Result(column="category_two", property="categoryTwo", jdbcType=JdbcType.VARCHAR),
        @Result(column="category_three", property="categoryThree", jdbcType=JdbcType.VARCHAR),
        @Result(column="source", property="source", jdbcType=JdbcType.VARCHAR),
        @Result(column="attribution", property="attribution", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="user", property="user", jdbcType=JdbcType.VARCHAR),
        @Result(column="type", property="type", jdbcType=JdbcType.VARCHAR)
    })
    List<ExpertsCdLog> selectByExample(ExpertsCdLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts_cd_log
     *
     * @mbggenerated Sun Jun 11 21:49:49 CST 2017
     */
    @Select({
        "select",
        "id, experts_id, name, gender, age, school, degree, work, title, phone, remarks, ",
        "leader, bacteria, category, category_two, category_three, source, attribution, ",
        "CREATE_TIME, user, type",
        "from experts_cd_log",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="experts_id", property="expertsId", jdbcType=JdbcType.INTEGER),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="gender", property="gender", jdbcType=JdbcType.VARCHAR),
        @Result(column="age", property="age", jdbcType=JdbcType.VARCHAR),
        @Result(column="school", property="school", jdbcType=JdbcType.VARCHAR),
        @Result(column="degree", property="degree", jdbcType=JdbcType.VARCHAR),
        @Result(column="work", property="work", jdbcType=JdbcType.VARCHAR),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="phone", property="phone", jdbcType=JdbcType.VARCHAR),
        @Result(column="remarks", property="remarks", jdbcType=JdbcType.VARCHAR),
        @Result(column="leader", property="leader", jdbcType=JdbcType.VARCHAR),
        @Result(column="bacteria", property="bacteria", jdbcType=JdbcType.VARCHAR),
        @Result(column="category", property="category", jdbcType=JdbcType.VARCHAR),
        @Result(column="category_two", property="categoryTwo", jdbcType=JdbcType.VARCHAR),
        @Result(column="category_three", property="categoryThree", jdbcType=JdbcType.VARCHAR),
        @Result(column="source", property="source", jdbcType=JdbcType.VARCHAR),
        @Result(column="attribution", property="attribution", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="user", property="user", jdbcType=JdbcType.VARCHAR),
        @Result(column="type", property="type", jdbcType=JdbcType.VARCHAR)
    })
    ExpertsCdLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts_cd_log
     *
     * @mbggenerated Sun Jun 11 21:49:49 CST 2017
     */
    @UpdateProvider(type=ExpertsCdLogSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ExpertsCdLog record, @Param("example") ExpertsCdLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts_cd_log
     *
     * @mbggenerated Sun Jun 11 21:49:49 CST 2017
     */
    @UpdateProvider(type=ExpertsCdLogSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ExpertsCdLog record, @Param("example") ExpertsCdLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts_cd_log
     *
     * @mbggenerated Sun Jun 11 21:49:49 CST 2017
     */
    @UpdateProvider(type=ExpertsCdLogSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ExpertsCdLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experts_cd_log
     *
     * @mbggenerated Sun Jun 11 21:49:49 CST 2017
     */
    @Update({
        "update experts_cd_log",
        "set experts_id = #{expertsId,jdbcType=INTEGER},",
          "name = #{name,jdbcType=VARCHAR},",
          "gender = #{gender,jdbcType=VARCHAR},",
          "age = #{age,jdbcType=VARCHAR},",
          "school = #{school,jdbcType=VARCHAR},",
          "degree = #{degree,jdbcType=VARCHAR},",
          "work = #{work,jdbcType=VARCHAR},",
          "title = #{title,jdbcType=VARCHAR},",
          "phone = #{phone,jdbcType=VARCHAR},",
          "remarks = #{remarks,jdbcType=VARCHAR},",
          "leader = #{leader,jdbcType=VARCHAR},",
          "bacteria = #{bacteria,jdbcType=VARCHAR},",
          "category = #{category,jdbcType=VARCHAR},",
          "category_two = #{categoryTwo,jdbcType=VARCHAR},",
          "category_three = #{categoryThree,jdbcType=VARCHAR},",
          "source = #{source,jdbcType=VARCHAR},",
          "attribution = #{attribution,jdbcType=VARCHAR},",
          "CREATE_TIME = #{createTime,jdbcType=TIMESTAMP},",
          "user = #{user,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ExpertsCdLog record);
}