package com.medicineCenter.dao;

import com.medicineCenter.model.dataObject.Task;
import com.medicineCenter.model.dataObject.TaskExample.Criteria;
import com.medicineCenter.model.dataObject.TaskExample.Criterion;
import com.medicineCenter.model.dataObject.TaskExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class TaskSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public String countByExample(TaskExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("task");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public String deleteByExample(TaskExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("task");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public String insertSelective(Task record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("task");

        if (record.getTaskId() != null) {
            sql.VALUES("task_id", "#{taskId,jdbcType=INTEGER}");
        }

        if (record.getInspectionUnit() != null) {
            sql.VALUES("inspection_unit", "#{inspectionUnit,jdbcType=VARCHAR}");
        }

        if (record.getLeaderId() != null) {
            sql.VALUES("leader_id", "#{leaderId,jdbcType=VARCHAR}");
        }

        if (record.getBacteria() != null) {
            sql.VALUES("bacteria", "#{bacteria,jdbcType=VARCHAR}");
        }

        if (record.getStartExecutionTime() != null) {
            sql.VALUES("start_execution_time", "#{startExecutionTime,jdbcType=VARCHAR}");
        }

        if (record.getState() != null) {
            sql.VALUES("state", "#{state,jdbcType=VARCHAR}");
        }

        if (record.getSource() != null) {
            sql.VALUES("source", "#{source,jdbcType=VARCHAR}");
        }

        if (record.getCreateUser() != null) {
            sql.VALUES("create_user", "#{createUser,jdbcType=VARCHAR}");
        }

        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }

        if (record.getEndExecutionTime() != null) {
            sql.VALUES("end_execution_time", "#{endExecutionTime,jdbcType=VARCHAR}");
        }

        if (record.getAttribution() != null) {
            sql.VALUES("attribution", "#{attribution,jdbcType=VARCHAR}");
        }

        if (record.getChecktype() != null) {
            sql.VALUES("checktype", "#{checktype,jdbcType=VARCHAR}");
        }

        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public String selectByExample(TaskExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("task_id");
        } else {
            sql.SELECT("task_id");
        }
        sql.SELECT("inspection_unit");
        sql.SELECT("leader_id");
        sql.SELECT("bacteria");
        sql.SELECT("start_execution_time");
        sql.SELECT("state");
        sql.SELECT("source");
        sql.SELECT("create_user");
        sql.SELECT("create_time");
        sql.SELECT("end_execution_time");
        sql.SELECT("attribution");
        sql.SELECT("checktype");
        sql.FROM("task");
        applyWhere(sql, example, false);

        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }

        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Task record = (Task) parameter.get("record");
        TaskExample example = (TaskExample) parameter.get("example");

        SQL sql = new SQL();
        sql.UPDATE("task");

        if (record.getTaskId() != null) {
            sql.SET("task_id = #{record.taskId,jdbcType=INTEGER}");
        }

        if (record.getInspectionUnit() != null) {
            sql.SET("inspection_unit = #{record.inspectionUnit,jdbcType=VARCHAR}");
        }

        if (record.getLeaderId() != null) {
            sql.SET("leader_id = #{record.leaderId,jdbcType=VARCHAR}");
        }

        if (record.getBacteria() != null) {
            sql.SET("bacteria = #{record.bacteria,jdbcType=VARCHAR}");
        }

        if (record.getStartExecutionTime() != null) {
            sql.SET("start_execution_time = #{record.startExecutionTime,jdbcType=VARCHAR}");
        }

        if (record.getState() != null) {
            sql.SET("state = #{record.state,jdbcType=VARCHAR}");
        }

        if (record.getSource() != null) {
            sql.SET("source = #{record.source,jdbcType=VARCHAR}");
        }

        if (record.getCreateUser() != null) {
            sql.SET("create_user = #{record.createUser,jdbcType=VARCHAR}");
        }

        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        }

        if (record.getEndExecutionTime() != null) {
            sql.SET("end_execution_time = #{record.endExecutionTime,jdbcType=VARCHAR}");
        }

        if (record.getAttribution() != null) {
            sql.SET("attribution = #{record.attribution,jdbcType=VARCHAR}");
        }

        if (record.getChecktype() != null) {
            sql.SET("checktype = #{record.checktype,jdbcType=VARCHAR}");
        }

        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("task");

        sql.SET("task_id = #{record.taskId,jdbcType=INTEGER}");
        sql.SET("inspection_unit = #{record.inspectionUnit,jdbcType=VARCHAR}");
        sql.SET("leader_id = #{record.leaderId,jdbcType=VARCHAR}");
        sql.SET("bacteria = #{record.bacteria,jdbcType=VARCHAR}");
        sql.SET("start_execution_time = #{record.startExecutionTime,jdbcType=VARCHAR}");
        sql.SET("state = #{record.state,jdbcType=VARCHAR}");
        sql.SET("source = #{record.source,jdbcType=VARCHAR}");
        sql.SET("create_user = #{record.createUser,jdbcType=VARCHAR}");
        sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        sql.SET("end_execution_time = #{record.endExecutionTime,jdbcType=VARCHAR}");
        sql.SET("attribution = #{record.attribution,jdbcType=VARCHAR}");
        sql.SET("checktype = #{record.checktype,jdbcType=VARCHAR}");

        TaskExample example = (TaskExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    public String updateByPrimaryKeySelective(Task record) {
        SQL sql = new SQL();
        sql.UPDATE("task");

        if (record.getInspectionUnit() != null) {
            sql.SET("inspection_unit = #{inspectionUnit,jdbcType=VARCHAR}");
        }

        if (record.getLeaderId() != null) {
            sql.SET("leader_id = #{leaderId,jdbcType=VARCHAR}");
        }

        if (record.getBacteria() != null) {
            sql.SET("bacteria = #{bacteria,jdbcType=VARCHAR}");
        }

        if (record.getStartExecutionTime() != null) {
            sql.SET("start_execution_time = #{startExecutionTime,jdbcType=VARCHAR}");
        }

        if (record.getState() != null) {
            sql.SET("state = #{state,jdbcType=VARCHAR}");
        }

        if (record.getSource() != null) {
            sql.SET("source = #{source,jdbcType=VARCHAR}");
        }

        if (record.getCreateUser() != null) {
            sql.SET("create_user = #{createUser,jdbcType=VARCHAR}");
        }

        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }

        if (record.getEndExecutionTime() != null) {
            sql.SET("end_execution_time = #{endExecutionTime,jdbcType=VARCHAR}");
        }

        if (record.getAttribution() != null) {
            sql.SET("attribution = #{attribution,jdbcType=VARCHAR}");
        }

        if (record.getChecktype() != null) {
            sql.SET("checktype = #{checktype,jdbcType=VARCHAR}");
        }

        sql.WHERE("task_id = #{taskId,jdbcType=INTEGER}");

        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    protected void applyWhere(SQL sql, TaskExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }

        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }

        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }

                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }

                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }

        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}