package com.medicineCenter.dao;

import com.medicineCenter.model.dataObject.TaskInspectionInfo;
import com.medicineCenter.model.dataObject.TaskInspectionInfoExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface TaskInspectionInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_inspection_info
     *
     * @mbggenerated Thu Feb 23 14:28:40 CST 2017
     */
    @SelectProvider(type=TaskInspectionInfoSqlProvider.class, method="countByExample")
    int countByExample(TaskInspectionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_inspection_info
     *
     * @mbggenerated Thu Feb 23 14:28:40 CST 2017
     */
    @DeleteProvider(type=TaskInspectionInfoSqlProvider.class, method="deleteByExample")
    int deleteByExample(TaskInspectionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_inspection_info
     *
     * @mbggenerated Thu Feb 23 14:28:40 CST 2017
     */
    @Delete({
            "delete from task_inspection_info",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_inspection_info
     *
     * @mbggenerated Thu Feb 23 14:28:40 CST 2017
     */
    @Insert({
            "insert into task_inspection_info (id, task_id, ",
            "inspection_unit, attribution, ",
            "checktype)",
            "values (#{id,jdbcType=INTEGER}, #{taskId,jdbcType=INTEGER}, ",
            "#{inspectionUnit,jdbcType=VARCHAR}, #{attribution,jdbcType=VARCHAR}, ",
            "#{checktype,jdbcType=VARCHAR})"
    })
    int insert(TaskInspectionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_inspection_info
     *
     * @mbggenerated Thu Feb 23 14:28:40 CST 2017
     */
    @InsertProvider(type=TaskInspectionInfoSqlProvider.class, method="insertSelective")
    int insertSelective(TaskInspectionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_inspection_info
     *
     * @mbggenerated Thu Feb 23 14:28:40 CST 2017
     */
    @SelectProvider(type=TaskInspectionInfoSqlProvider.class, method="selectByExample")
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="task_id", property="taskId", jdbcType=JdbcType.INTEGER),
            @Result(column="inspection_unit", property="inspectionUnit", jdbcType=JdbcType.VARCHAR),
            @Result(column="attribution", property="attribution", jdbcType=JdbcType.VARCHAR),
            @Result(column="checktype", property="checktype", jdbcType=JdbcType.VARCHAR)
    })
    List<TaskInspectionInfo> selectByExample(TaskInspectionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_inspection_info
     *
     * @mbggenerated Thu Feb 23 14:28:40 CST 2017
     */
    @Select({
            "select",
            "id, task_id, inspection_unit, attribution, checktype",
            "from task_inspection_info",
            "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="task_id", property="taskId", jdbcType=JdbcType.INTEGER),
            @Result(column="inspection_unit", property="inspectionUnit", jdbcType=JdbcType.VARCHAR),
            @Result(column="attribution", property="attribution", jdbcType=JdbcType.VARCHAR),
            @Result(column="checktype", property="checktype", jdbcType=JdbcType.VARCHAR)
    })
    TaskInspectionInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_inspection_info
     *
     * @mbggenerated Thu Feb 23 14:28:40 CST 2017
     */
    @UpdateProvider(type=TaskInspectionInfoSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TaskInspectionInfo record, @Param("example") TaskInspectionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_inspection_info
     *
     * @mbggenerated Thu Feb 23 14:28:40 CST 2017
     */
    @UpdateProvider(type=TaskInspectionInfoSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TaskInspectionInfo record, @Param("example") TaskInspectionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_inspection_info
     *
     * @mbggenerated Thu Feb 23 14:28:40 CST 2017
     */
    @UpdateProvider(type=TaskInspectionInfoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TaskInspectionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_inspection_info
     *
     * @mbggenerated Thu Feb 23 14:28:40 CST 2017
     */
    @Update({
            "update task_inspection_info",
            "set task_id = #{taskId,jdbcType=INTEGER},",
            "inspection_unit = #{inspectionUnit,jdbcType=VARCHAR},",
            "attribution = #{attribution,jdbcType=VARCHAR},",
            "checktype = #{checktype,jdbcType=VARCHAR}",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TaskInspectionInfo record);
}