package com.medicineCenter.dao;

import com.medicineCenter.model.dataObject.Task;
import com.medicineCenter.model.dataObject.TaskExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface TaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    @SelectProvider(type=TaskSqlProvider.class, method="countByExample")
    int countByExample(TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    @DeleteProvider(type=TaskSqlProvider.class, method="deleteByExample")
    int deleteByExample(TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    @Delete({
            "delete from task",
            "where task_id = #{taskId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    @Insert({
            "insert into task (task_id, inspection_unit, ",
            "leader_id, bacteria, ",
            "start_execution_time, state, ",
            "source, create_user, ",
            "create_time, end_execution_time, ",
            "attribution, checktype)",
            "values (#{taskId,jdbcType=INTEGER}, #{inspectionUnit,jdbcType=VARCHAR}, ",
            "#{leaderId,jdbcType=VARCHAR}, #{bacteria,jdbcType=VARCHAR}, ",
            "#{startExecutionTime,jdbcType=VARCHAR}, #{state,jdbcType=VARCHAR}, ",
            "#{source,jdbcType=VARCHAR}, #{createUser,jdbcType=VARCHAR}, ",
            "#{createTime,jdbcType=TIMESTAMP}, #{endExecutionTime,jdbcType=VARCHAR}, ",
            "#{attribution,jdbcType=VARCHAR}, #{checktype,jdbcType=VARCHAR})"
    })
    @Options(useGeneratedKeys = true, keyProperty = "taskId")
    int insert(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    @InsertProvider(type=TaskSqlProvider.class, method="insertSelective")
    int insertSelective(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017——
     */
    @SelectProvider(type=TaskSqlProvider.class, method="selectByExample")
    @Results({
            @Result(column="task_id", property="taskId", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="inspection_unit", property="inspectionUnit", jdbcType=JdbcType.VARCHAR),
            @Result(column="leader_id", property="leaderId", jdbcType=JdbcType.VARCHAR),
            @Result(column="bacteria", property="bacteria", jdbcType=JdbcType.VARCHAR),
            @Result(column="start_execution_time", property="startExecutionTime", jdbcType=JdbcType.VARCHAR),
            @Result(column="state", property="state", jdbcType=JdbcType.VARCHAR),
            @Result(column="source", property="source", jdbcType=JdbcType.VARCHAR),
            @Result(column="create_user", property="createUser", jdbcType=JdbcType.VARCHAR),
            @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="end_execution_time", property="endExecutionTime", jdbcType=JdbcType.VARCHAR),
            @Result(column="attribution", property="attribution", jdbcType=JdbcType.VARCHAR),
            @Result(column="checktype", property="checktype", jdbcType=JdbcType.VARCHAR)
    })
    List<Task> selectByExample(TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    @Select({
            "select",
            "task_id, inspection_unit, leader_id, bacteria, start_execution_time, state, ",
            "source, create_user, create_time, end_execution_time, attribution, checktype",
            "from task",
            "where task_id = #{taskId,jdbcType=INTEGER}"
    })
    @Results({
            @Result(column="task_id", property="taskId", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="inspection_unit", property="inspectionUnit", jdbcType=JdbcType.VARCHAR),
            @Result(column="leader_id", property="leaderId", jdbcType=JdbcType.VARCHAR),
            @Result(column="bacteria", property="bacteria", jdbcType=JdbcType.VARCHAR),
            @Result(column="start_execution_time", property="startExecutionTime", jdbcType=JdbcType.VARCHAR),
            @Result(column="state", property="state", jdbcType=JdbcType.VARCHAR),
            @Result(column="source", property="source", jdbcType=JdbcType.VARCHAR),
            @Result(column="create_user", property="createUser", jdbcType=JdbcType.VARCHAR),
            @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="end_execution_time", property="endExecutionTime", jdbcType=JdbcType.VARCHAR),
            @Result(column="attribution", property="attribution", jdbcType=JdbcType.VARCHAR),
            @Result(column="checktype", property="checktype", jdbcType=JdbcType.VARCHAR)
    })
    Task selectByPrimaryKey(Integer taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    @UpdateProvider(type=TaskSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Task record, @Param("example") TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    @UpdateProvider(type=TaskSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Task record, @Param("example") TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    @UpdateProvider(type=TaskSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Tue Feb 14 16:43:38 CST 2017
     */
    @Update({
            "update task",
            "set inspection_unit = #{inspectionUnit,jdbcType=VARCHAR},",
            "leader_id = #{leaderId,jdbcType=VARCHAR},",
            "bacteria = #{bacteria,jdbcType=VARCHAR},",
            "start_execution_time = #{startExecutionTime,jdbcType=VARCHAR},",
            "state = #{state,jdbcType=VARCHAR},",
            "source = #{source,jdbcType=VARCHAR},",
            "create_user = #{createUser,jdbcType=VARCHAR},",
            "create_time = #{createTime,jdbcType=TIMESTAMP},",
            "end_execution_time = #{endExecutionTime,jdbcType=VARCHAR},",
            "attribution = #{attribution,jdbcType=VARCHAR},",
            "checktype = #{checktype,jdbcType=VARCHAR}",
            "where task_id = #{taskId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Task record);
}