package com.medicineCenter.dao;

import com.medicineCenter.model.dataObject.TaskLog;
import com.medicineCenter.model.dataObject.TaskLogExample;
import com.medicineCenter.model.dto.TaskLogDTO;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface TaskLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_log
     *
     * @mbggenerated Fri Oct 21 16:10:17 CST 2016
     */
    @SelectProvider(type=TaskLogSqlProvider.class, method="countByExample")
    int countByExample(TaskLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_log
     *
     * @mbggenerated Fri Oct 21 16:10:17 CST 2016
     */
    @DeleteProvider(type=TaskLogSqlProvider.class, method="deleteByExample")
    int deleteByExample(TaskLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_log
     *
     * @mbggenerated Fri Oct 21 16:10:17 CST 2016
     */
    @Delete({
            "delete from task_log",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_log
     *
     * @mbggenerated Fri Oct 21 16:10:17 CST 2016
     */
    @Insert({
            "insert into task_log (id, task_id, ",
            "orig_experts_id, new_experts_id, ",
            "reason, create_time, create_user)",
            "values (#{id,jdbcType=INTEGER}, #{taskId,jdbcType=INTEGER}, ",
            "#{origExpertsId,jdbcType=INTEGER}, #{newExpertsId,jdbcType=INTEGER}, ",
            "#{reason,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, #{createUser,jdbcType=VARCHAR}) "
    })
    int insert(TaskLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_log
     *
     * @mbggenerated Fri Oct 21 16:10:17 CST 2016
     */
    @InsertProvider(type=TaskLogSqlProvider.class, method="insertSelective")
    int insertSelective(TaskLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_log
     *
     * @mbggenerated Fri Oct 21 16:10:17 CST 2016
     */
    @SelectProvider(type=TaskLogSqlProvider.class, method="selectByExample")
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="task_id", property="taskId", jdbcType=JdbcType.INTEGER),
            @Result(column="orig_experts_id", property="origExpertsId", jdbcType=JdbcType.INTEGER),
            @Result(column="new_experts_id", property="newExpertsId", jdbcType=JdbcType.INTEGER),
            @Result(column="reason", property="reason", jdbcType=JdbcType.VARCHAR),
            @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<TaskLogDTO> selectByExample(TaskLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_log
     *
     * @mbggenerated Fri Oct 21 16:10:17 CST 2016
     */
    @Select({
            "select",
            "id, task_id, orig_experts_id, new_experts_id, reason, create_time",
            "from task_log",
            "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="task_id", property="taskId", jdbcType=JdbcType.INTEGER),
            @Result(column="orig_experts_id", property="origExpertsId", jdbcType=JdbcType.INTEGER),
            @Result(column="new_experts_id", property="newExpertsId", jdbcType=JdbcType.INTEGER),
            @Result(column="reason", property="reason", jdbcType=JdbcType.VARCHAR),
            @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    TaskLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_log
     *
     * @mbggenerated Fri Oct 21 16:10:17 CST 2016
     */
    @UpdateProvider(type=TaskLogSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TaskLog record, @Param("example") TaskLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_log
     *
     * @mbggenerated Fri Oct 21 16:10:17 CST 2016
     */
    @UpdateProvider(type=TaskLogSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TaskLog record, @Param("example") TaskLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_log
     *
     * @mbggenerated Fri Oct 21 16:10:17 CST 2016
     */
    @UpdateProvider(type=TaskLogSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TaskLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_log
     *
     * @mbggenerated Fri Oct 21 16:10:17 CST 2016
     */
    @Update({
            "update task_log",
            "set task_id = #{taskId,jdbcType=INTEGER},",
            "orig_experts_id = #{origExpertsId,jdbcType=INTEGER},",
            "new_experts_id = #{newExpertsId,jdbcType=INTEGER},",
            "reason = #{reason,jdbcType=VARCHAR},",
            "create_time = #{createTime,jdbcType=TIMESTAMP}",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TaskLog record);
}